app:
    resource: "@AppBundle/Controller/"
    type:     annotation
notlogged:
    path: /notlogged
    defaults: { _controller: AppBundle:Success:notLogged }
user-panel:
    path: /user-panel
    defaults: { _controller: AppBundle:Success:userPanel }
edit-news:
    path: /edit-news
    defaults: { _controller: AppBundle:News:editById }