# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

#services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
services:
    app.simplefile:
        class: AppBundle\Utils\SimpleFile
    app.addtags:
        class: AppBundle\Utils\AddTags
        arguments: [ doctrine.orm.entity_manager  ]
    app.form.type.edituser:
        class: AppBundle\Form\Type\EditUserType
        tags:
            - { name: form.type alias: EditUserType }
    app.form.type.user:
        class: AppBundle\Form\Type\UserType
        arguments:
                    - 'username'
                    - 'password'
        tags:
            - { name: form.type alias: UserType }
